### PR TITLE
Notebooks2

### PR DESCRIPTION
**Pull request by vkt1414**
This PR address #5

- Described what each notebook does and tried to improve the readability of the notebooks.
- Provided a sample papermill command wherever applicable

### CODE REVIEW

**Comment by fedorov** [comment]
@vkt1414 is it necessary to keep the output cells in the notebooks?

**Comment by vkt1414** [comment]
> @vkt1414 is it necessary to keep the output cells in the notebooks?

Not necessary..would you like me to clear the output for all notebooks?

**Comment by fedorov** [comment]
Here are suggested updates:
* remove output (to make it easier to open the notebook in GitHub)
* do not use `aws_url` in any intermediate queries to reduce complexity and cost
* start using `CONCAT(aws_bucket,'/',crdc_series_uuid)` for forming the series folder path
* instead of pasting the binary of the images, let's keep all images in a dedicated folder, and insert them by references (you can see an example in https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/getting_started/part1_prerequisites.ipynb - but don't use dropbox links like I did for that notebook - let's put the links into "images" folder, for example)

Once these are fixed, let's just merge this, and I will review by experimenting with the notebooks.

**Review by fedorov — CHANGES_REQUESTED** [review]
see earlier comment

**Comment by vkt1414** [comment]
> * remove output (to make it easier to open the notebook in GitHub)

Done

> * do not use `aws_url` in any intermediate queries to reduce complexity and cost
> * start using `CONCAT(aws_bucket,'/',crdc_series_uuid)` for forming the series folder path

   Will be addressing these from sqlqueryfix branch

> * instead of pasting the binary of the images, let's keep all images in a dedicated folder, and insert them by references (you can see an example in https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/getting_started/part1_prerequisites.ipynb - but don't use dropbox links like I did for that notebook - let's put the links into "images" folder, for example)

Done

> Once these are fixed, let's just merge this, and I will review by experimenting with the notebooks.

Please go ahead

**Review by fedorov — APPROVED** [review]

**Pull request merged**
